---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: storage
spec:
  encryptedData:
    rootPassword: AgBPfGnlJ/Tm7BFs8jPkSsvqgw6QJLsuFxXShvogYbc0giO9JsaSKQfIkfvXGstdAnpSNj6VbLZxkUialLFHiFAigNc4tGFyLMlXYkJEUv8CLfN7+nYcPvzBqcVp2sydJDv+EgpY5Xfs2niNowq+2rmuPhODyjciCUl4dUWiBE3ZkO2Zrn/+kZYg+ZcewWMHfIasac6Zzi+LjXPMGx5eX0XmONqysdtcEbEBHQ7MmJHtObjsPeOZsOA07WwK0jCKViUGByZ0qmqYb0VBRuep7KpDBZKuZeEXrofAY6iGZARVkA6x8xUn7xlkMHe5d/R4gVpYjFh53xN4bHgNwyCn6nazJH7tMLd6meaVmj58buVshkRVRUDHbMC1Q8l38BGJWPeuxSZxMjZ0c0AoBJAmdMush35zfJcpe3Sgrp2kHQ68p92CGzU5+P/9Xq8fGRfUVCAonFZ5t1ugBeJk0u8y5bNwKzuzIoJ4sdRIOe/sasX51xR82hBqmYdEmu3yqOuce5VWx7Qpe65TqVqX0XY+0oWGOmiUsEH8n1W6pfJhZlaA4pGqgRLKk60UoPvvVtad3XqktZ5aFzTWs7+PBwB5290dusOu1evlhg9uIUuH/qhBM9t/ks8fKiMYbOr32Q8lxFj6dlU+G2wQkTIbnqIcjqKAYV887/KGkkHEY6xXqANLRWKFtc9aAQQklqdkYzlZhVWMoYTexuHBz+VXfojOWvjQkYQE5Fki2HYU8i5kS/BsVYUacKvW9uZ9mjoAeQ==
    rootUser: AgCRHN3PAAPnCldcUNlX5XHLyznNC4acw4lpYtWTe5j+5bB84GkFO2CCqHFvU2fk3nPm9B7Oe1zCvJtJxUhI3RZJovBdUqDXiEvhaNM1PTMuchZWn7rHVHay6MNWIhl/e20ya17QzxpZNcfJTjaZl/oHWnWNucFb2QgrYhhB5q1XwopPL31lCcJ1E/vYOdd4B04/9RijC0xwJdLeVhYUQgnENWcptdIGMs9hCu9K2aG1V5rQb5Gagq7k0jshR+HvOQ4JHnEV77tKSt4x6PUw+R/UVQ0USOFeF2Y0FuL2TeCvJFYic4UG4rUmLF8s/Jewgr9LoSF3iKsWJqUzZD3PnqzvrXWceevAmor0tYxIANB2E0Se2pSqhtpXxyJL03Q/RYGXw83c7aTEbdiY5MTyphDiQXgMuZqJ/tgHTuqrjXQOIGXThFngi5Y8E1yvD+HptRnhsMStCAw4C92AMEGw1yxK3dJBs7RFUfzgZQrAzrrfzHbSK1DE6JkzB9p5WX9R4fhH2oADHcIvLSPIjfx6Gk2MdtV7ko/Xv1ZRqy2JtLXTZ6HwtVYDm7D7v2Lifhd6r2Pgo2H3jzNnd7+7QTxmggpfGNM9udmK1vXwSmvkQ99/pd+L8s2jkyJcFa9Q/AoeCG5VOzVXbnxmnQy8mrFP6quffOlkoeM9k2k0O3upQZ+riScFGU17RiqwLlqn6Inf3KrMlqeesg==
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: storage
