apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkding-secret
  namespace: linkding
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-global
    kind: ClusterSecretStore
  target:
    name: linkding-secret
    creationPolicy: Owner
  data:
    - secretKey: OIDC_RP_CLIENT_ID
      remoteRef:
        key: "linkding-oidc-client-id"
    - secretKey: LD_DB_PASSWORD
      remoteRef:
        key: "linkding-postgres-password"
    - secretKey: LD_SUPERUSER_NAME
      remoteRef:
        key: "linkding-superuser-name"
    - secretKey: LD_SUPERUSER_PASSWORD
      remoteRef:
        key: "linkding-superuser-password"
    - secretKey: OIDC_RP_CLIENT_SECRET
      remoteRef:
        key: "linkding-oidc-client-secret"
