---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-admin-secret
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgCtdtrb56HBJAUKvFh8sOHMxV6HjDpGmj8UnbWatBnU19deVGArK35jZmS5a7NWg+dJRhNkOFT1f8+uFjPtIn7hBPBaLisI64SQ577qn7j5gqvyGzbRL1w8MGpFWWaA1Sg9/Cp/3DnQPG8PgQcb8H6gt2aUNNlSiLlJTwHMqBnZW/ztz+o4gITlGgUz240mvNbEs/DaQ1b9qAuLkVNYbTUt+lZAkm0xpFR0vyxofY7ZDjTDr7mXApA2xWjpsn3eHC48lAf0BCnnNwinwYLrru58po9MyeaB7zhN5JuWbes7gk2v00QTA2Oe/y9KfNutDalIKZYB74U5o3Q/teAGa0pQx6goic5Wb0SFfasM4mnlbis2aK/CGkV6bk6gnudOzl9ObNuetwcNxCOM1uFnCbd3KvTrcW26Ut9W68n9pb4uCfky+h2kOLnALBGdM1K82A3dkiYbEogwJ44r82SQWDPOGXNk/eAIGt1zZ/30ES5F61OIOuyeUkhyGKwINPQEqcVJRIYtyBe9loVUmfdApRd5X5H0kW++1wriq/4entPYKzb8JcIJfQ3BP59boe0YBngHYJZ2uDGMzQ6gLfJwCuuNCEnPceLgP5AYG3jpZKJV0VUBUghU7n9B4/sYZEDx6TyQQJsTrNNLvFnOT+bkUbsekgplt+OsGnz2UojsXiZ046cW7xuBypEyY5rZ3xHIcSjJsxrzYMnuPem6/mHZUtyM812t1pByRfeqFn0LjBQtjXE/5NGM0mNEyt90
  template:
    metadata:
      creationTimestamp: null
      name: harbor-admin-secret
      namespace: harbor
