---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-postgresql-secret
  namespace: harbor
spec:
  encryptedData:
    password: AgCmn+xev2owZFi6fA/hTgdaXpW3Z+IuhVbTc7N0DNMxWfi9arRPcxv85MSfEE2i26SgNDW87gWIAEIQ2FrLs8nL3byddWJKm6Dnw0Wxc4ony/qVmeKjdasIqQPTBtOgOYuria4vFG8v2CxlJEnOnW4Xe/sX+NZRMudTMFC3hGVlPTwqpiXEEMVKOk6OgohVKihhcWhVVQ/Y5sR8RQ2zSL008h2DBOQe9zRNGPzPSqkC48YPRCGAVEWlXtKHSB6oI5t4qX5P2wnGyxcx4ONSFxqivDsEmSkItkxMGhSCib+ULOcQFNB+1Ch4JYeHL2xwX1RznWauIrZ8mplm69TcAzK15VIgLH7fbEIreBR9RR6+WAqGh2sRZuDFi5izCgqVXHLJATQ9xRkR0j0wiXv2Wg3RTkyqmaERfsOlklJ1zvSxwyMRZWk0Vesi9kNPwJkex3gmaxO6P3KK3ARQyzfNnZkAb89B5L137oJj+thqzk2smYeUDtg3FEHzaq/UMrTR6bUrUQNvx+S4kcptKNS8vz6kA53BznBubARyIXFT3gw2WF2jaxvu7kwuvv8wKmfm/uHas1cuceDF3+OKNvNYphGPVGjVtow4w05R4RhnjIMm/w6TdzSmyE9Mfx+/wNXfv8qaHQTCzqxSRLb6JHheUK4/CnlFJ7ArAeKnTerUAhmzSH/ubI1MpYAUp09axjmPrVlFSqXQ8Y69wJkxF5FOJbbFR7hPSc4SK3tl
  template:
    metadata:
      creationTimestamp: null
      name: harbor-postgresql-secret
      namespace: harbor
