apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-ssd-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "10.5.1.5"
    path: "/volume1/k3s-ssd/harbor"
  mountOptions:
    - nfsvers=4.1
    - hard
    - intr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry-storage
  namespace: harbor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  volumeName: harbor-ssd-pv
