---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-oidc-config
  namespace: harbor
spec:
  encryptedData:
    CONFIG_OVERWRITE_JSON: AgB0QntTeLxUrt9lvFajpT89YEIDF0zeWoB7B55/wjSUKYEDVkvHvdsasZIoBfIyJp3OKHpUl1qVbtIYUhXV3ruE/MMDGKiL2nRSkHF5B7Qww3tqS+pdr6CibYEiq64Oxc+bmUNIbRgSfqsuBgaJS++F0lUPkfkJjoKqH6zaARJR/FSlUNb5gWmA19bQTey5zySAE98Eo2JzVq/s6fjOu0iJpjsLOXjIJdROCW30xeDJDde+lM5qJtB8tI/LRqqdk4/U3ejwC9l2UipUM5P95X7NLRQkyg2DG8MV07ZK0xwJxfZIM/T7QCkfiB4okpScPP3CgvEbi9z2+ccumgXWqUgpMhhSl8IyKVxojh3LcYEdjeFAkI7M2lY6SwBbNkEZtiKSmoDpqb4gbUpHf3Lvh3Y+xQlRBjmSe8QlfHshrzAPTjW7vsIwqrXDDsgblWOmT8juqiITLpCz+DxwNKLUZJXNo25lXbAg2w1/c3zL/UNNxpwC2zYH2d7dVzJV1qDO8gn0yMvNf+2UDhtmhpo3IE6guqSA/Nvd1r8YW4gt3FnrK2WyA/myVkOvtsr6dQLec8101F48zaBHDRymPVflW++oPdx9VhwolTqRyKNFAwPgaZzU6353YnqbgN30Q62VdORxRy8XoD9AkSJqH+3bxAMOe/kpVV771FGjJTJGqq3aP9KHlO/xEScE+VPv5eWgq1Aapqn3RVreO6Cjdbq//KL3sci/LbEvoSO2JF2ocr+FZ4COqlkRN/shELefdISjVD8HjCV1rlUGEjqnJmrMkgYYlaVC39hCTAEOwvfOoMs8v+9JPSrNrKgQYCithnH4G7PVbFVipS8u8RHZcdZ304C+IMZrfNU3G3yrwDo2X9TGJIHvUGNEBVFqSRoo4Keq9bDgykz2WoCG1GGGqR2pAK6Ze202uaaHHqH7HBRP2xrUyrJ5SuiSX5CQnBVSYr+PIXNoXSB7fMeWOk7Bf8FGIR5HMtWPKQSE+MzpPXxXr8giGKA6fCuJiSK2RsNa8/Ubim110fjWj5z3nNlkZdj7afg23J0aashZySg4e48YH1ZdqI+fd6NSdyekOBY7QeYeOiAbvAOStieOHZD1TOkRJS3L9Zf5Zk+7F4mTOS9K7UOvJrt6JXa4HECiYBhkBaoreKd8nUpbrZ2Zq1/nxkdWAFBuiwHZ4br1TClvTJrbrLKFQe0Bnkl6AoKr8fEXJ0PPRdAcOlOltiPjpyWpBM3BbcbF+Kt32cabwXnXnkcOyOkEsWY4gFOQcCznVyv3EhZpBJkagSKZD5lEjn7nZqLjIkRBh/urHGe8i7EQZaq/lp63xB0QDLJBs2HENA8UyhVRzFQ1vaPtfa5UAbStOrb8kPo=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-oidc-config
      namespace: harbor
