---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-runner-secret
  namespace: gitea
spec:
  encryptedData:
    GITEA_RUNNER_REGISTRATION_TOKEN: AgCNlKsRNJexHQmauaCzLXIOqbL9bs6rdEpuPksgMVU1g1gazoUQh6XCnTSXkdlt2CYtZcrvy3zYC87ZKxkknN96gn0QO/RfVXdLcu2EVEMXqZ30Upjv6dvW3kcplENehcJbwYZfgSX48fFp+Ay16doqUEw4I55/3zDPD/3ZxLuTZaVrGLWJ/QlU61CCf2zj+U4AR/T+sJ1hZqV0Yo2IHtun42DRaO0+CrcQ4TsmTkikrCX8xKq/JkABUSEv2Gx/T7Kpl6/l1BAxVTNWKXPLVeXR1eNJFy8a4gO13SPdELK4KSwaj1nLY1jkjjU/cJE4cDkep0xdblvfuPBSB7ywQFG5FF4ONeLrH9TlWI2V61VpHczAIx6/K8UBIEOW2/dZpdPqPhThdIvEs+0beM5gcNTnWH1jwZmMzHw236uTQoIDyYFM41p2l9+TWqAaoDnA0RUNuUvo1Ql+eH7giThHtIFlLKTCWL2be1AxUKLRTnOTMydvvJB2bVvLd+9aL37v6OpJ7mXLgxhOsQueIIjVEZRKg8fGPW4bnkSgTN3MljvMpRAaiyPSrQJzPqtiAqOJ/IW35Qx+m9zrcbhNkNcGSxXRHDBxB9vt2+t7iCNnPSp82K31kI6YyL8UhCK66r4X/5mnHko9FKzlxN0ZILWs7l0/+DT7wrNBbStF/NOH1Mm8Bz8UrAwG3USmmk2EcQfZ6JsHx0zCFp2YMgeBzXGx1KkNGmIlLhX6Ob1HUakvSuGbEE9GO+GJGDs0
  template:
    metadata:
      creationTimestamp: null
      name: gitea-runner-secret
      namespace: gitea
    type: Opaque
