apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outline-app-secret-bws
  namespace: outline
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-global
    kind: ClusterSecretStore
  target:
    name: outline-app-secret-bws
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: "outline-secret-key"
    - secretKey: utils-secret
      remoteRef:
        key: "outline-utils-secret"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outline-db-secret-bws
  namespace: outline
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-global
    kind: ClusterSecretStore
  target:
    name: outline-db-secret-bws
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: "outline-postgres-password"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outline-minio-secret-bws
  namespace: outline
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-global
    kind: ClusterSecretStore
  target:
    name: outline-minio-secret-bws
    creationPolicy: Owner
  data:
    - secretKey: access-key-id
      remoteRef:
        key: "outline-minio-access-key-id"
    - secretKey: secret-access-key
      remoteRef:
        key: "outline-minio-secret-access-key"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outline-oidc-secret-bws
  namespace: outline
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-global
    kind: ClusterSecretStore
  target:
    name: outline-oidc-secret-bws
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: "outline-oidc-client-secret"
