---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: outline-db-secret
  namespace: outline
spec:
  encryptedData:
    postgres-password: AgAUQ2XD9OLSDZq+lt9XpT8ewMP+Yiu3yvwg7P4bH0y1ruVORFgKshOgH+op2r227F8daW3WruxrIMtsv+RX73MEpkt7+ppFm5KoSeNyixMJJWdsJLg9IneCB9oCqBcNQtc8fvxwIj6ZHQ2e+NCwROIX/m5NPRuLq33eo3AKet/s1le6TRYy3oz6hV7N8hjBu9YkoOKMVVnszufHzcOwgnSEctKxRxyM1eDPIFNehVDQfUyFH6CLypVwgf+4Wv/Tll68x/sINx5w9wjQVAIRvuwzK4A/JS8siij2lyz+I3PllaTjCJGcEs795FUxRv36z0qFfqvhyZtPK/2oMCLbyHhCVojFfXK8NbKp8Wtf48ewA/sHcYAcLxFY4xcCtasmTTvuLu2GxwDg7ToI+ZouEifvypQz93uZdhDiO74/JwOOfkn7oGNyfm677M9NR3wt4HaAvbKP/gxpqoW4r33osTqhx1Du2+b02AcrTAVeoLEyr3DL0Io+emhQkspKx28qMgNskFghekr6mx201+FF7+3b9Af4pKvadmicqH8edhNcg6oixtesiQX6kpPawVF17iKGH9HabBvK//x8YzXJxoCVUZoeW6I/qHq2XhwdoRS5vv9HFvBZ5J19xbT6huCar7IlSGLrRLuExz3y+nZV3Mr/hyTtZbYiOGKw/z0/59lN8YJfIMmTELqGo+8vAo9m25zu8rhPfwdzTTxhC2Bdbsr9khtzx/rDeGDBLzGQkO4MDP/3lz3cYbpMz0/y1A==
  template:
    metadata:
      creationTimestamp: null
      name: outline-db-secret
      namespace: outline
