---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: outline-minio-secret
  namespace: outline
spec:
  encryptedData:
    access-key-id: AgCboXx39lT+BkoYDlChd8ETYr2EscOCiWd3hYA8pnUrgMYpIGWEcYeDEVluzzGleOY7v/XM2KXTRso8YVFtdHWChAG/Hd4ZGKrnV8SxrHapxFYAFUXsT8pWOUO/BnxyQ9lrMmU9Ww+OTI88mrbGW9vtA1ElegDlk7Ps8QNQo+ZhHU/uteR4MVk3NTmcfg+2Sbb2qJqLsZ3lZpKiC2hvKWPPXy1Uv5GZYrGcfOaabrTZZkRROqi/mVF4kTRn1zR1iEpZ1haimpuqrD3WE7vrYCpkvTJwdJ3+Xx8wfjUKCVM1X2bscJ8OHKIWe9Cf6Y8/YdtHqzkhSb4SsBtORlPAmjTWAbywKfIXZZlFliSlpHW0h3uzh7804ZJ48gbGU6mRs4LphUIzPkHSaTITxZ9lZ6yUMaKwcIjtb37CGZmMpIY+UZS47F52REm++fAwdz1gdVZPDOQY+T8J7TGIEMSf9x9zAqnIQdoaCIwc+2u4LqY06D0NIOYI2ChjCiWRlVP7uQg1oFJp/Kg053ze/JL8CawUedZZHe1Fxt+12c0xGKQ0ocQynv2pT33eJW4R/gz/QlUcuBomMfmJy4sInpMNdcnZBpuoLhJNCdzDunqMd6LHH4QAcIc8X2CM6Id325fMlab1QRIjNhcm8aMxwWZSlFKBo//RVt7tZfv0YlC6uOlaf/6AbTZnldmAPLs3VZH2fOV7t0YAd+5T
    secret-access-key: AgAmwUzbML9bcMD6ZVQIfS1L6ov1JmCtzBdsKp/UYX2AEmre4z5/wUQ4W4gOJj6nHz9BbecA9wqwTZ/FEPv0Z7ybKKcpO75ve/DViE2HzbNoYkmPJtZKYSr5mEGS2NhOSuqjD4iA1z8bTAe/VSIwBTZO1TiWWchNTTuolzO2WVG3LfTZC9rLzUNh1YfpGxxRIHk+Il0Jbgthjl4HvZp8qKgA8nzFdUdEpQ+Du/UQqb6bpqxR43t2Etq93B+nMdBZOvcH5Q5S7OkI397hDHrXqPfsw+8G8ynwN7kJfnp1CtYLH6mQDNbVGDdRCTbpMsNqfERNgLGfG3QMWzkyleJFucTcc0Jkr18v0vOo79riNBZWJpoiMHiJiHrwEY3QjKPRIzzcqxz7Q9MVBLKzFQYlqUTZpuBDfhVyeJgFSSTHQiX2vwWz1hL7xlwxl13Hfh45NSFQ5cXQ6Qi94kn4GGyuZJ0zZo3ewOE6Z/1PAoWHvYUzghqxyi9vpTT0hdztqOyJQds0aUzYHTV8kArxWSwKbpUbZth5NSjq9oXXmZ6PW9N5rLAisHxtGA7xFH4b8EJ78QAeTzZ08cdzwRGrthwtzEVqCNWjtM6SrC7QaucCXceAtBr6QUgQZgccFI/tKu9elJWU31ve4N61rI9xMmbAsJacJSwMPf/4vOzsGb4gO+zT5gMkeerOKXgtJnWEWpecmgQkGTEZzu/9B/GVyJiQUHjcEPrGXK/a0Uq/1u6ZChC5u5dRRb8HjN2PePBF4A==
  template:
    metadata:
      creationTimestamp: null
      name: outline-minio-secret
      namespace: outline
