---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: outline-db-secret
  namespace: outline
spec:
  encryptedData:
    postgres-password: AgB8YFPBaf186cU6OmeChDA4EUMTWK9xI7xMspO09G2iJT6qOid62Lh+8dA6gL4AvN80dK6eCGrcLLLeHilj+8LvpJZ2XnNmjv74xtjMkGKX7bz6kDMW5zXic4THMu71cMLXp/trHeWXV1Cz7R2XXaxS70p6pzzob7RfSDR9H4CuehKqCiffDor0hq5DboAaSB3npnP2KfneE5WyqMDsqG4fE9n7rXr2yCA6dARiJQfDm7e5YNY8Tk+4cnLEgtPElL7Ym8+uOwbghEjJlYUw8WQ4UguLiOFCQEbuefhHYS99zKlwphj8AMVWy0GtpiS5Vop38D4tEzcnxuCfnoAsLy3O8KDslnURbTI7pihtDfImeB1wjTnec9YMDdVTBhg3o90G/2Fce/l9QOwauZd4wz+gr+IoMMJb6IPsUpC7aBvrHgIFIzkSB0bgz/7C+hYcHvgN2cTxx+8a0KMYzYW3NQxlO1kC8NeGwslBGKV8Gz+LCyUv2lZ1CO8VeoP96vyVzWNjc3yle+6Yi1o1iHeAvqkzoDQln9uyyqZwEsF3oi+YW4mwutDQ3KK+DDACep+r26wWPjF9xPu9+/t5uAISJXSUkahoqzSEE9wxuB6D4aThBbv00jjNoGD0MxkxlZVvQHHLdx369ddlDxEGpmfY0bpJgpbjqMy6cxxmkq6NYg6aHMN/30I+acrap/L+0DscRIQIwHzVWcWQRElYYxad1YiasweYCQ==
  template:
    metadata:
      creationTimestamp: null
      name: outline-db-secret
      namespace: outline
