---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: outline-app-secret
  namespace: outline
spec:
  encryptedData:
    secret-key: AgA+1DeKTK/PhaEDNzK/QDvPUG9PtD5md6DtN9UHM2tUg5PFUbxDOTy7fVduOzKeewtZ5wzeNG75V1nhb7IQ2NcgZbhritywgyb8XIId9UdO0oyKU9S60waq10zmxIywvM1GU8zwVR2VKovtuCtCEMKMV1223j5gh02JS+M2196RUwduS3jLHmq4ReKEzRwJzgGpYv39ZaQJq+OmJoAp6o9N6YOfwB0GSGAuNYZu7+clHKMFCwzExdXL0d/wwx6JMJ4Z0k5Tsjm5X1niQieTC8yvtHIN/FZO4D9T470EONOHphg8/shxSQc92h9VJhksbCQ17p2MDP0WIjFj9FMhuiZo6Lzz1tX7J3laHCS9YmKdXbMbD6b3X3wy8GqgFbpBsLUUM3iOef5kG8uRubJkyWjN34cI+qRjT9Z1qWwBSJdS28uhIWDKCW67osghS5YAeQWAMVHyqdcw4mPntE3Mj/jzc3kA6XbUViUh0iAkBNJR6fSliVkYHNGJZmi9qlG2iUpLBpSqSRE3ftYUuq62K3HzT57FiM7Q0Mxztpm+YEUUV71IK3KYdvml187fzq7X9Sc0PEVyXHMFCfvG41Eo2zf9v+62IhZ++Y+u3O++EFIVRvJg3PYYtdqrqPj3TegsZDasekiKbjoukXAo9f+quF+BUmb1j5Bn5RYO71+FzuEQGBpgfx8tYWeM06JikRbHmne+pPgzbqHmdHDfI/9ocxtj7AWZ26PscqHwA64ze0BPquty8NiFitfd24vOpCQMgudF8gIH86F/sMDTDdoN4b2X
    utils-secret: AgB2DEV7ja9YSbw6/OlmQxEdp1iOLkU0k5IxZZ0iNedUZcA9jsrsRf2vhTu64SJmkwGS4I4ppumutVeG4rBJabctUymRRKX/OyKJ4+OpaqPrVNHaS6z6vrUgl90hliOoED2q7SrClW+KOnmAs08YSmFanX3YwAwn6IprU3PGWKdTsY8cA4y72R8h2j8ZZo7x/8Q86ZwKUsPMxd6BDyXBCPuBUAvhfKo2NRmAb9wF6YoJK6HDm0QPPC+fOYsmJNhK0MO2Jo4DBOMYEyS2XiLau35DdAioCQiA7nFf58FDApS1YGPJQqknVXdsgUTyBQV59BrI7lVreD3MMQP6EdZefbOMrTocvfehiQtsOHED88fZbRCK+r+gpqV8HRZyzTYU8EIae88vk6byoU8cAuVwQDfzSbcd9AxTt5dNZM8Aa/NE6KNYTDCiMqqDbeiSnEwGJ95oPaBFJXRmwBfynjVhvdB7FuVgbWgkBJvGlmDoUZA/cNH6wLxUWN8GyVsT+ZzBM9ek84nbguw0EqEoOszSIW5fiiNW/KAdlVIqtgC0+VaAGm9wdZ1AACKDoQ5bFjTf2NpnsugJmlYOFZrxgpoqhfRnU7Q25+Y5u/nQTBD/kWdMBNIuSKABAF3143RxUu7IG/dmY71SX+BLymGAQM9PWmRiDaVzV8zFntglpQQiAlK0ksBHNRdr3kYgw9oYOMSYngTTSvEOi229GAsmZGVNocjnqI3ExKwHxDSyVRZ/bzVe6psdKmna0HmqI3MTBMvYW+EugmlHka4nnqpCUJnQJ6OO
  template:
    metadata:
      creationTimestamp: null
      name: outline-app-secret
      namespace: outline
