---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: outline-oidc-secret
  namespace: outline
spec:
  encryptedData:
    client-secret: AgACVwpBnw9OXbI+DtQ8+O2bYj+YmX+x1ZSuCHXspTLDnKIwhaR9KEaq89TeZehVWNulqpHcLgaQsRmQ0aRMmcDZD4bzZXO0BgULnuD+tP9p8yvVuzrSuW2fZi7tOhzMl0mecskby37Q72iaHx0inn6qlpWQSOEZ15+EtizkFX9r3ioYFM0agdHTOSZI9gWAu2l6V/em9SFgVJmqTbJqD2PuWIhhktS9UsAwekpBoNM8DC6q4BnGlff1oZPIzthjkJzrrnrnXPUsgScQR4w0WXkK5B1jNqdullTMnyTVzgmjcOpxUv2vPKVtmIr1l36QRryjwJYKh05R8QyLVv/RarNbsSdbjR4WRd23IbY7PL+woOJ+vnzNxp8MnAEovwzWBP5rWVrxFfHFHAAW690/ZCCwVrqRJIUExU7qa6uupbZbZxrycYqeOf0MVbZWPAgijRoci74t1LeUV0YAfsH3YYgFOeMdWhWpubCNhcPD52xitT9/ptM6OR1JdCmNGawK4qgAKuqjdBm5DAiGg0QyivQoWxj+vk2QWpcpTTAUn6GAzG5BesTm/J87C+3dTM6exnnUpT4Dv+RtxMmfiEVPVhgiXApfvJpl7nbbVF4WVS1YzFeW5JA86thb6Rvz5YlPEIU4LxC6lBirM7BNq8lsvrr1Ux5agHAcLnUGZBlbK8CIX9nURMQsuQLkjtbTOyzA3AGT7opYsCMoY++Wcb1p2zLGQ2g4bBH+2mnocGjlgAHiKxcSsP3WU5KdEPn1gg/vqvHevw0IlU31zrLqp8qlyUJyuuD+DO1A9VgiEZWalG3tMJD7/+3af2luLZ09pdX/49kSkNCOIjUYa0Y45+QwN1kjlTPjFCexumGwNw99mBZW2w==
  template:
    metadata:
      creationTimestamp: null
      name: outline-oidc-secret
      namespace: outline
