apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opengist-secret
  namespace: opengist
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-global
    kind: ClusterSecretStore
  target:
    name: opengist-secret
    creationPolicy: Owner
  data:
    - secretKey: OG_SECRET_KEY
      remoteRef:
        key: "opengist-secret-key"
    - secretKey: OG_OIDC_CLIENT_KEY
      remoteRef:
        key: "opengist-oidc-client-id"
    - secretKey: OG_OIDC_SECRET
      remoteRef:
        key: "opengist-oidc-client-secret"
