apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opengist-data
  namespace: opengist
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-ssd
  resources:
    requests:
      storage: 5Gi
