apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: bitwarden-test-store
  namespace: bitwarden-test
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      organizationID: "67346aa4-4dc2-45a3-b269-b2f800c9ad03"
      projectID: "aaca560d-8421-45be-8151-b41c00e0d0ea"
      auth:
        secretRef:
          credentials:
            name: bitwarden-access-token
            key: token
      bitwardenServerSDKURL: "https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998"
      # Base64 de ca.crt (o tls.crt si no existe ca.crt) desde el Secret bitwarden-tls-certs
      caBundle: "REPLACE_BASE64_CA_CRT"
