apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: bitwarden-test-store
  namespace: bitwarden-test
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      organizationID: "67346aa4-4dc2-45a3-b269-b2f800c9ad03"
      projectID: "aaca560d-8421-45be-8151-b41c00e0d0ea"
      auth:
        secretRef:
          credentials:
            name: bitwarden-access-token
            key: token
      bitwardenServerSDKURL: "https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998"
      # Base64 de ca.crt (o tls.crt si no existe ca.crt) desde el Secret bitwarden-tls-certs
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYekNDQWtlZ0F3SUJBZ0lSQUxhb0JmYVR3M1U5Sm83T1czOFZEME13RFFZSktvWklodmNOQVFFTEJRQXcKQURBZUZ3MHlOakEwTURFd09UTXlNak5hRncweU56QTBNREV3T1RNeU1qTmFNQUF3Z2dFaU1BMEdDU3FHU0liMwpEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURFRkg1YU9ZakE3Uk1DWStCYVZic3h3cGxrdkpJaVBKelpzMWhSCnp0WmUrZ1JrWUJLQTJMZTcvQlZaMWVQWVp1RFdwWDk3TGRiZUJ0MXBBbm1PVGNDSm90WlcxM3c5Wm9NRkh5ZDQKNkdMV1Q4dElMYkw5M2liVWRZekU4V29aWHk1UUZDTGx0czFxanNhNWh6Z3M0c2IxbEN4SnVvbEx2dmZtcU9uMwo2WEtuZGRWb2xobjVGdVlIaHJlaUlHZlA0Z1NOVHREOUdqd1YvUm9CSDE3Y1VwVHBnRVVuTHRpdyttYkk5d25DCmpEZlcwSmlHdEZ4cmVTT2xaejZVMHZieU5yeXJGQnNLT0cweWFhNkF2VWswZE0zUkRRU3NUdjNCRGVsSnBuMXcKQm12VGQ4ODl5UTNRQ0NRZ0ZZWHA5bll2cDE1NmdpQk9pRi9aMlYwNlFSNUNJZmxEQWdNQkFBR2pnZE13Z2RBdwpEZ1lEVlIwUEFRSC9CQVFEQWdXZ01Bd0dBMVVkRXdFQi93UUNNQUF3Z2E4R0ExVWRFUUVCL3dTQnBEQ0JvWUlVClltbDBkMkZ5WkdWdUxYTmtheTF6WlhKMlpYS0NKV0pwZEhkaGNtUmxiaTF6WkdzdGMyVnlkbVZ5TG1WNGRHVnkKYm1Gc0xYTmxZM0psZEhPQ0tXSnBkSGRoY21SbGJpMXpaR3N0YzJWeWRtVnlMbVY0ZEdWeWJtRnNMWE5sWTNKbApkSE11YzNaamdqZGlhWFIzWVhKa1pXNHRjMlJyTFhObGNuWmxjaTVsZUhSbGNtNWhiQzF6WldOeVpYUnpMbk4yCll5NWpiSFZ6ZEdWeUxteHZZMkZzTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCcHVqRWp4NEJaUnZSK2FTemYKN09qTzFpaVdBMG56eTZIWWdHcXNHaXNrczlkWFRsMmFCTW5DdHd2b1BidVpiWEREc0VZVEVjdlBES2VGL1N6UgpFWUgrZTZTSForNjViL2tiTklhWDRvSFlSNjdaOWZ3MmNQQTBKU0ZLNUFvY0ZEa0ZQaUp0VElQTHREWmxaamROCmI3cVVRUVRQTm5HZFNTUk83ZldqQ0JRNTE4b0lEa1BBMWpxT0ppS0tKMGZmdUhyQXEydzZpS1A0bHV1dkwwSUcKTzZ1UHJ3b3pDOW85Y0JTU2xLNWpsY3o5QTBLTFZUY3ZENkl0THg2cWY2c0pLR1NObFFzaVRQb0NxNElpQ2p5UAp1TXhmcHFXQXRzM1BydjJVaEk4MU02cTFxUEtRSG03UXI5c3FCRklBK2NxbmU1UnVLSWlobEFuL1NtN05WSzI2CnZOcE4KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
