apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: outline
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://community-charts.github.io/helm-charts
      chart: outline
      targetRevision: 0.7.3
      helm:
        valueFiles:
          - $values/apps/outline/values.yaml
    - repoURL: https://github.com/cubancodepath/homelab-argocd.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/cubancodepath/homelab-argocd.git
      targetRevision: HEAD
      path: apps/outline/config
  destination:
    server: https://kubernetes.default.svc
    namespace: outline
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
