apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-outline-gitops
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "5"
data:
  outline-gitops.yaml: |
    version: 1
    metadata:
      name: outline-gitops
    entries:
      - model: authentik_providers_oauth2.oauth2provider
        identifiers:
          name: outline-gitops
        attrs:
          name: outline-gitops
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          client_id: "${OUTLINE_GITOPS_CLIENT_ID}"
          client_secret: "${OUTLINE_GITOPS_CLIENT_SECRET}"
          redirect_uris: "https://outline.cubancodelab.net/auth/oidc.callback"
          signing_key: !Find [authentik_crypto.certificatekeypair, [name, "authentik Self-signed Certificate"]]
      - model: authentik_core.application
        identifiers:
          slug: outline-gitops
        attrs:
          name: Outline GitOps
          slug: outline-gitops
          provider: !Find [authentik_providers_oauth2.oauth2provider, [name, "outline-gitops"]]
