apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-ssd-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "10.5.1.5"
    path: "/volume1/k3s-ssd/gitea"
  mountOptions:
    - nfsvers=4.1
    - hard
    - intr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-shared-storage
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: gitea-ssd-pv
