---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-authentik-secret
  namespace: gitea
spec:
  encryptedData:
    key: AgAILdT3MTrpebkma6l8dowwmMSjqiywS1qIJdVfl8gP+nvJ8uCBeyIq30MZIk/ukC14HI+DOT/DYffyxQABRZU89Nb6Angu3SyjZ837hM7JgkuQDq4gwN+i4lJjg5QTvuw+WI9Qy56CWtzBlr41TdE9LxXaT3ydrPhrVvcqFQ3o6M9m40pXUmm8oLKUu+qrxCVolzeqJMBFWKVDien0aqtDfO1kTjhua5MjdaBHtwxiR/g1b22/i06Eq3OhyCSWmKAOOF3uWb+6x4u1JHJBxs/S9ihiFnnB43qyM9B+Iqds8cFnnf8QlrkioBHVC/6N2ggz/cmzpcI4/ymGerAIwt7AWlyHvS60QrkQ0O0MEA5SrRAMHNKvSsNs/ky7rLQvEnVN4kRiw1fBq9kkoHuddcZrHR907C3sskjiRkjMPlBdmJD2Tt4arN000Do8NMyEB3+VJMo9MaoZRs3tebYZ79/Yt0Yf+YvP8LOzArOAyF2eROoduYgscskYOfuzFVyTFjlxMDJ96T+nsxZLUryGDxROjq6J97q7fU1NcYX57PjUGs7qlsquS6OvV9hg2tspKwI+DRRDhEOXQqExoQFWvjGcUksd6kpo6Sk4jFe7wmNEdEDW1k9jRJZ0i1Xh6jpxXVQbYjyuzRooEcmMVO32pL6q3qPWpnG4BPn1VM9EaceibgrLZAMHlulowHw9MI5oDJ1vhIs6fELZKnrK6xrlVT/3YBeQfgWgmuESlQzTfa9GMsTkBjsrKuW5
    secret: AgCSc3hhBBYF7afkYMM/vkbgZrd6YBb5TW80xHc92acsJ/oe9HHUqOnl2AIwkqIOA77M5ysXADzZi7By05m35tf/U0rFmpzDmWWuqC66QTyrGmqeIi1jHnNCO3F0NdRWnz8TlrYsfsqF6MyCoDtQB9BNBbEX1WUSxeuqNPVg6RZ45B+tsvPdZgb90PEjKVlMEmB4H65ZLmw5Fy7f7JRfCutRGhf5Rz/+BCDE6bPdjf7L9fgCfTBKK5ewcdvHdYYUjqfYXyVv7EteqIRUWvLeAwr+zwk0i0a0rIdrAMUruGmfy0RhCzhjVFXN/CQsAX8mWll2EwUQcHkrj98wJKLmD/WuxAlQ1KMy6xj035moqr84fj6Jv4j1atwPmCzIMYLdOQ9+xVCF/MavkXFUcabCFXQZMS5xpJpFKHGjF1cH/3HMmd0jdkgK0jDocGNolJDAx3N+RRbSuOwnGiCdmV1mLQPO/c7XKt2eCxQsYl8FpekQQmDQUKfJ6Gd8fzXkAr+1CcxsX+/NijAlfLWejTwHUvH4rBFWHn3HUBDaClOfWQPp0sb+KTMGWvinrj846/pmE/U9cXobjI5BUYbom5Lo7Ul4V/IbCyB4c8+7mfz+cghHVtf3pUf3qxsHsjXqCnElBvSu04Dl5NQL2egPSjvUg99QSkoHgvdJDjgHMtHPWu+QP7L9DkBdv6NRuVmXMcb/N3ufIl35rGGz/2N8//mbR1ipnBg3UHmv12r1LaITU+TJku0wINx1LmIXhdpnOswMsZEwlYsu/xUZ/m7XhwfcA58/p2n7Z9ucLtKbZw3noNCpR4ho1uofmF55oTrVKn7j9LUIR2bgk/AQcbLlodYqiw3xe8SJbY+CVkSuEVQg1lpKJQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitea-authentik-secret
      namespace: gitea
    type: Opaque
