---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-authentik-secret
  namespace: gitea
spec:
  encryptedData:
    client-secret: AgCidrUonJZn1XcYUJ8UM8X2jWjBMXwtje1eRHF/4Mpb5NKlZUAwkjeSdcG2ACYg2r3voXtj9vRX5LdFojYB9XWvBJ3xrgU8wP+yVLMbRrJ5ehKXNgAjKp2yvIB0KAWML9l1QJGUoDaOaGNvrTZD6Dg5oXsOCnCfsKgFbp6oJfFXzDE2RTO9BHQqU3IIBoVacauUWQTmHc12XSQPDOyFe8UAY712a5c4t61Ju40qTLh6x3VQxIRi+R9ik0T/iktGCs0DekaszJRUpauKgAq4JcMK0MFCr1MgVXYkfs7Rt4AwNj7tHJDi/E3LAcZ4kllzExrCgoDJNqPXXzkmkpTm/XS+P7lJgf9iKvDIR2Sb3NocON8Ra4oQgKKUv8EV+LUBcCsnK9A7mszwHtwWlIDHtg6SeO9C/t+ke1YMz7Yy8l022fqiqzlwl1eF++qvQhrouTVa3Rsfcts9Tzduip95EvICqXocI5HNvB9V45uZEjwI19FAWvVt5MyXjx8CHsqhEGlVxdkot/HsVxUD7GKTmOGtnLTKXBe/PfSNjZktwFb4uApamPlQW4Kxc1Px8FC0Wp9TXH2c1CZIJAtywsYOBgqQ4Kf9DhkWA7Z4sueV5iurgA2YCfq5utcod32Tay3NOAAAhAu/PkUJ8z28hyjAMuN4d34KCr7jZnxNb0Irihci/as8JIY0R6O0foHHOkyQzTXMAIAdZTJX7/MSV/JcEpt0cXfNvf+3Y7u5+ah9pRpNzJ3999ZWJhdFHSaB6M4SOpWC30s7HvnHD/Jn4PTn8ecSwdDDEQtnT8EHcmAQVznskZ+Z88Gh2tCZD+eknCpc/Fx2a1N/esUMfnJ7P2PU1fYp4j4SJK9ajeIaaz7s/4dF2Q==
  template:
    metadata:
      creationTimestamp: null
      name: gitea-authentik-secret
      namespace: gitea
    type: Opaque
