apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-pv
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "10.5.1.5"
    path: "/volume2/Immich"
  mountOptions:
    - nfsvers=4.1
    - hard
    - intr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Ti
  volumeName: immich-library-pv
