apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-secret
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-global
    kind: ClusterSecretStore
  target:
    name: immich-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: "immich-postgres-password"
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: "immich-redis-password"
    - secretKey: JWT_SECRET
      remoteRef:
        key: "immich-jwt-secret"
