---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: database
spec:
  encryptedData:
    password: AgBI3P/rcpCRpTv/DBg0ozyngnpQFdW8QqewizdriBrR+gE4XgRm4flH+PYSL7dsAZN0lfA8tMbdUNgOmAFDFfzKGgWiko/umxAfBrKGYeZpXHOi801MjkkRS319Li/k9UCFOyL10cx2tbzvUKClhatnqUJhxClxvi2g+EufAKVDBIc1d7ZVRcIT1iE24EM7u2x/5oRewqg5iCGLOgxJBdA3jA7FykVJNcCQ2/rpnYw9gQePuiDkhP/wqYCYSmqEoo00yFRFY6sh8ldsUFE23RQ0rtR1OUGL8UqGnWS8UBY8C/Gbco8RanrxCY1Z1mn2TDnPhbVQy3spwrJS4AUXBZ6e68MVAxX/cxl/W4KG6yosXh/p336AIF+whryLLO5KRYEJiYS01pdLjCaMCjsjaIEDlc3EKSf5MIW9zEiHQihH3QnGlO+Xr0rt/pY8EXST6sxHyeXmV/2s/pQPLLRNm5/Trphrw5zg60K8fqIMiYa7ett/hAtAOSGvidqucY4t014a1SgNX/omhnirC5fXkE9lPPvPmaSE7w9zAaxGcNS+iKq85b9DZTyor/5Tsh7sLlFjysCQCCNVyBnGWfdlmbI5ReBI2ak6UEBNQqRIQYmHuNMAemjmLwJrccArMfFVshw7MWlD/JjHESQkfByQb9Pwv/BY9x57Z6Cm7te9wCvIpBUK4o3P49UnGq9v13WX4Rfx04PL997g+w7sLDz4MeRv08wrEBL3LTY0Ij5CEQtj8xMlSnyI9qeJYRwVvg==
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: database
