apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: 1.18.3
      helm:
        valueFiles:
          - $values/apps/harbor/values.yaml
    - repoURL: https://github.com/cubancodepath/homelab-argocd.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/cubancodepath/homelab-argocd.git
      targetRevision: HEAD
      path: apps/harbor/config
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
