apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-admin-secret-bws
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-global
    kind: ClusterSecretStore
  target:
    name: nextcloud-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: nextcloud-username
      remoteRef:
        key: "nextcloud-admin-username"
    - secretKey: nextcloud-password
      remoteRef:
        key: "nextcloud-admin-password"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-db-secret-bws
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-global
    kind: ClusterSecretStore
  target:
    name: nextcloud-db-secret
    creationPolicy: Owner
  data:
    - secretKey: db-username
      remoteRef:
        key: "nextcloud-db-username"
    - secretKey: db-password
      remoteRef:
        key: "nextcloud-db-password"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-redis-secret-bws
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-global
    kind: ClusterSecretStore
  target:
    name: nextcloud-redis-secret
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: "nextcloud-redis-password"
