apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: silverbullet-secret
  namespace: silverbullet
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-global
    kind: ClusterSecretStore
  target:
    name: silverbullet-secret
    creationPolicy: Owner
  data:
    - secretKey: SB_USER
      remoteRef:
        key: "silverbullet-user"
