apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-plane-minio-vol-plane-minio-wl-0
  namespace: plane
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-hdd
  resources:
    requests:
      storage: 20Gi
