---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plane-minio-data
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: "10.5.1.5"
    path: "/volume1/k3s-ssd/plane/minio"
  mountOptions:
    - nfsvers=4.1
    - hard
    - intr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-plane-minio-vol-plane-minio-wl-0
  namespace: plane
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
  volumeName: plane-minio-data
